//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwapiFrontEndWPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwapiFrontEndWPF.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Age.
        /// </summary>
        public static string AverageAge {
            get {
                return ResourceManager.GetString("AverageAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Height.
        /// </summary>
        public static string AverageHeight {
            get {
                return ResourceManager.GetString("AverageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Year.
        /// </summary>
        public static string BirthYear {
            get {
                return ResourceManager.GetString("BirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating....
        /// </summary>
        public static string Calculating {
            get {
                return ResourceManager.GetString("Calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while calculating data..
        /// </summary>
        public static string ErrorCalculatingData {
            get {
                return ResourceManager.GetString("ErrorCalculatingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while connecting to database..
        /// </summary>
        public static string ErrorLoadingData {
            get {
                return ResourceManager.GetString("ErrorLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female Ratio.
        /// </summary>
        public static string FemaleRatio {
            get {
                return ResourceManager.GetString("FemaleRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The height has to be a floating point number and greater than 0..
        /// </summary>
        public static string HeightValidationError {
            get {
                return ResourceManager.GetString("HeightValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Wars Persons Overview.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male Ratio.
        /// </summary>
        public static string MaleRatio {
            get {
                return ResourceManager.GetString("MaleRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass.
        /// </summary>
        public static string Mass {
            get {
                return ResourceManager.GetString("Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection available.
        /// </summary>
        public static string NoDataWasFound {
            get {
                return ResourceManager.GetString("NoDataWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Details.
        /// </summary>
        public static string PersonDetailDialogTitle {
            get {
                return ResourceManager.GetString("PersonDetailDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload data.
        /// </summary>
        public static string ReloadData {
            get {
                return ResourceManager.GetString("ReloadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Uri.
        /// </summary>
        public static string SelectionPath {
            get {
                return ResourceManager.GetString("SelectionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year must be in the format &apos;XXXXBBY&apos; or &apos;XXXXABY&apos;.
        /// </summary>
        public static string YearValidationFormatError {
            get {
                return ResourceManager.GetString("YearValidationFormatError", resourceCulture);
            }
        }
    }
}
